[package]
name = "touchbar-googleballs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
drm = "0.14"
input = "0.8"
libc = "0.2"
nix = { version = "0.27", features = ["fs", "ioctl"] }
